# Generated by Django 4.2.13 on 2024-09-17 00:50

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='categoryFacultet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
            ],
            options={
                'verbose_name': 'Fakultet',
                'verbose_name_plural': 'Fakultetlar',
            },
        ),
        migrations.CreateModel(
            name='categoryYunalish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
            ],
            options={
                'verbose_name': "Yo'nalish",
                'verbose_name_plural': "Yo'nalishlar",
            },
        ),
        migrations.CreateModel(
            name='talabalar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('lastName', models.CharField(max_length=200)),
                ('photo', models.ImageField(blank=True, default='Photo/user.jpg', upload_to='Photo/')),
                ('number', phonenumber_field.modelfields.PhoneNumberField(blank=True, help_text='Enter phone number', max_length=128, region=None)),
                ('guruh', models.CharField(max_length=10)),
                ('fakultet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.categoryfacultet')),
                ('yunalish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.categoryyunalish')),
            ],
            options={
                'verbose_name': 'Talaba',
                'verbose_name_plural': 'Talabalar',
            },
        ),
    ]
