# Generated by Django 5.1.1 on 2024-09-18 05:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('myapp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='talaba',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='talaba',
            name='fakultet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.categoryfacultet'),
        ),
        migrations.AddField(
            model_name='talaba',
            name='yunalish',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.categoryyunalish'),
        ),
    ]
